# Generated by Django 3.0.3 on 2020-02-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('idActivite', models.AutoField(primary_key=True, serialize=False)),
                ('nomActivite', models.CharField(max_length=50, verbose_name='nom  Activite')),
                ('typeActivite', models.CharField(max_length=50, verbose_name='type Activite')),
                ('descriptionActivite', models.TextField(verbose_name='description Activite')),
                ('dateActivite', models.DateTimeField(blank=True, null=True, verbose_name='date Activite')),
                ('lieuActivite', models.CharField(max_length=50, verbose_name='lieu Activite ')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('idContact', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du visiteur')),
                ('email', models.CharField(max_length=50, verbose_name='Email du visiteur')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'messages des personnes',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('idVisite', models.AutoField(primary_key=True, serialize=False)),
                ('prenomGuide', models.CharField(max_length=50, verbose_name='prenom de guide')),
                ('nomGuide', models.CharField(max_length=50, verbose_name='Nom de guide')),
                ('ville', models.CharField(max_length=50, verbose_name='ville de guide')),
                ('adresse', models.CharField(max_length=50, verbose_name='adresse de guide')),
                ('tel', models.CharField(max_length=50, verbose_name='telephone de guide')),
                ('mail', models.CharField(max_length=50, verbose_name='mail de guide')),
                ('langue', models.CharField(max_length=50, verbose_name='langues de guide')),
                ('description', models.TextField(verbose_name='description de guide')),
                ('note', models.TextField(verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('idHotel', models.AutoField(primary_key=True, serialize=False)),
                ('nomHotel', models.CharField(max_length=50, verbose_name="Nom de l'hotel")),
                ('descriptionHotel', models.TextField(verbose_name="description de l'hotel")),
                ('noteHotel', models.FloatField(verbose_name="note de l'hotel")),
                ('lienHotel', models.CharField(blank=True, max_length=50, verbose_name=" lien de l'hotel")),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('idRestaurant', models.AutoField(primary_key=True, serialize=False)),
                ('nomRestaurant', models.CharField(max_length=50, verbose_name='Nom du Restaurant')),
                ('lieuRestaurant', models.CharField(max_length=50, verbose_name='Nom du Restaurant')),
                ('descriptionRestaurant', models.TextField(verbose_name='description du Restaurant')),
                ('noteRestaurant', models.TextField(verbose_name='note du restaurant')),
                ('lienRestaurant', models.CharField(max_length=50, verbose_name=' lien du restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('idTransport', models.AutoField(primary_key=True, serialize=False)),
                ('lienTransport', models.TextField(verbose_name='lien ')),
                ('typeTransport', models.CharField(max_length=50, verbose_name='type de Transport')),
                ('descriptionTransport', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='imagesHotel',
            fields=[
                ('idImageHotel', models.AutoField(primary_key=True, serialize=False)),
                ('imageHotel', models.ImageField(height_field='height_field', upload_to=None, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptourisme.Hotel')),
            ],
        ),
    ]
