# Generated by Django 3.0.3 on 2020-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('idHotel', models.AutoField(primary_key=True, serialize=False)),
                ('nomHotel', models.CharField(max_length=50, verbose_name='Nom de hotel')),
                ('descriptionHotel', models.TextField(verbose_name='description de Hotel')),
                ('noteHotel', models.TextField(verbose_name='note de Hotel')),
            ],
        ),
    ]
