# Generated by Django 3.0.3 on 2020-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptourisme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('idActivite', models.AutoField(primary_key=True, serialize=False)),
                ('nomActivite', models.CharField(max_length=50, verbose_name='nom  Activite')),
                ('typeActivite', models.CharField(max_length=50, verbose_name='type Activite')),
                ('descriptionActivite', models.TextField(verbose_name='description Activite')),
                ('dateActivite', models.DateTimeField(blank=True, null=True, verbose_name='date Activite')),
                ('lieuActivite', models.CharField(max_length=50, verbose_name='lieu Activite ')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('idContact', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du visiteur')),
                ('email', models.CharField(max_length=50, verbose_name='Email du visiteur')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Guidee',
            fields=[
                ('idVisit', models.AutoField(primary_key=True, serialize=False)),
                ('prenomGuide', models.CharField(max_length=50, verbose_name='prenom de guide')),
                ('nomGuide', models.CharField(max_length=50, verbose_name='Nom de guide')),
                ('ville', models.CharField(max_length=50, verbose_name='ville de guide')),
                ('adresse', models.CharField(max_length=50, verbose_name='adresse de guide')),
                ('tel', models.CharField(max_length=50, verbose_name='telephone de guide')),
                ('mail', models.CharField(max_length=50, verbose_name='mail de guide')),
                ('langues', models.CharField(max_length=50, verbose_name='langues de guide')),
                ('description', models.TextField(verbose_name='description de guide')),
                ('note', models.TextField(verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('idRestaurant', models.AutoField(primary_key=True, serialize=False)),
                ('nomRestaurant', models.CharField(max_length=50, verbose_name='Nom de Restaurant')),
                ('lieuRestaurant', models.CharField(max_length=50, verbose_name='Nom de Restaurant')),
                ('descriptionRestaurant', models.TextField(verbose_name='description de Restaurant')),
                ('noteRestaurant', models.TextField(verbose_name='note de Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('idTransport', models.AutoField(primary_key=True, serialize=False)),
                ('lienTransport', models.TextField(verbose_name='lien ')),
                ('typeTransport', models.CharField(max_length=50, verbose_name='type de Transport')),
                ('descriptionTransport', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='VisitGuidee',
            fields=[
                ('idVisit', models.AutoField(primary_key=True, serialize=False)),
                ('nomVisit', models.CharField(max_length=50, verbose_name='Nom de visit')),
                ('nomGuide', models.CharField(max_length=50, verbose_name='Nom de guide')),
                ('dateVisit', models.DateTimeField(blank=True, null=True, verbose_name='date de visit')),
                ('lieuVisit', models.CharField(max_length=50, verbose_name='lieu de visit')),
                ('capaciteMax', models.CharField(max_length=50, verbose_name='capacite max des visiteur')),
                ('capaciteActuelle', models.CharField(max_length=50, verbose_name='capacite actuelle des visiteur')),
                ('commentaire', models.TextField(verbose_name='commentaire')),
            ],
        ),
    ]
