# Generated by Django 3.0.3 on 2020-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptourisme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='visite',
            fields=[
                ('idHotel', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='prenom')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('telephone', models.CharField(max_length=50, verbose_name='telephone')),
                ('cni', models.CharField(max_length=50, verbose_name='cni')),
                ('nbr', models.CharField(max_length=50, verbose_name='date Arive')),
                ('date', models.CharField(max_length=50, verbose_name='nbr nuit')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.RemoveField(
            model_name='imageshotel',
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='imagesHotel',
        ),
    ]
