# Generated by Django 3.0.3 on 2020-02-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptourisme', '0002_auto_20200223_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visite',
            old_name='idHotel',
            new_name='idVisite',
        ),
        migrations.CreateModel(
            name='ImageHotel',
            fields=[
                ('idImageHotel', models.AutoField(primary_key=True, serialize=False)),
                ('imageHotel', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('idHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptourisme.Hotel')),
            ],
        ),
    ]
