# Generated by Django 3.0.3 on 2020-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptourisme', '0005_auto_20200223_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='imageHotel',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ImageHotel',
        ),
    ]
