# Generated by Django 3.0.3 on 2020-02-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptourisme', '0006_auto_20200223_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitGuidee',
            fields=[
                ('idVisit', models.AutoField(default='', primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=10, verbose_name='Nom ')),
                ('prenom', models.CharField(default='', max_length=10, verbose_name='prenom')),
                ('email', models.CharField(default='', max_length=20, verbose_name='email')),
                ('telephone', models.CharField(default='', max_length=12, verbose_name='telephone')),
                ('cin', models.CharField(default='', max_length=10, verbose_name='cin')),
                ('nbr', models.CharField(default='', max_length=2, verbose_name='nombre des visiteur')),
                ('date', models.CharField(default='', max_length=10, verbose_name='date de visite')),
                ('message', models.TextField(default='', verbose_name='message')),
            ],
        ),
        migrations.RenameModel(
            old_name='Ccontact',
            new_name='Contact',
        ),
        migrations.DeleteModel(
            name='visite',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lieuRestaurant',
            field=models.CharField(max_length=50, verbose_name='lieu du Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nomRestaurant',
            field=models.CharField(max_length=50, verbose_name='nom du Restaurant'),
        ),
    ]
