# Generated by Django 3.0.3 on 2020-02-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptourisme', '0007_auto_20200223_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitGuidee',
            new_name='VisiteGuidee',
        ),
        migrations.RenameField(
            model_name='visiteguidee',
            old_name='idVisit',
            new_name='idVisite',
        ),
    ]
